package com.example.pokemonrepository.repository

import com.example.pokemonrepository.data.PokemonRepositoryItem
import com.example.pokemonrepository.repository.datasource.PokemonDataSource
import com.example.pokemonrepository.repository.datasource.local.PokemonLocalDataSource
import com.example.pokemonrepository.repository.datasource.remote.PokemonRemoteDataSource
import com.example.pokemonrepository.usecase.GetPokemonList
import com.example.pokemonrepository.usecase.GetPokemonListInteractor

class PokemonRepositoryService(override val getPokemonList: GetPokemonList): PokemonRepository